# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "105f8c2833b42c90e4598fe9b50a930c"
name = "my shop qr app"
handle = "my-shop-qr-app"
application_url = "https://sight-recipients-score-peru.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cat-person-vn.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sight-recipients-score-peru.trycloudflare.com/auth/callback",
  "https://sight-recipients-score-peru.trycloudflare.com/auth/shopify/callback",
  "https://sight-recipients-score-peru.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
